version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: coverage
  make-tag:
    docker:
      - image: circleci/node:10.11-stretch
    working_directory: ~/repo2
    steps:
      - checkout
      - run:
          name: Initialize git command settings.
          command: |
            git config user.email "circle-ci@users.noreply.github.com"
            git config user.name "CircleCI"
      - run:
          name: Version incriment patch.
          command: npm version patch -m 'version auto incliment. [skip ci]'
      - run:
          name: Push master branch and make tag.
          command: |
            git push
            git push origin --tags
workflows:
  version: 2
  build_and_version_up:
    jobs:
      - build
      - make-tag:
          requires:
            - build
          filters:
            branches:
              only: master
